/**
 * GET /api/workbooks/[id]/pdf?type=student|teacher
 *
 * Returns a PDF blob generated by @react-pdf/renderer.
 * Requires authentication — only the workbook owner can access it.
 *
 * DESIGN.html §7: Architecture — PDF generation via @react-pdf/renderer
 */

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/auth/supabase';
import { db } from '@/lib/db';
import { workbooks, questions, rubrics, users } from '@/lib/db/schema';
import { eq, and } from 'drizzle-orm';
import { isSupabaseConfigured, APP_ORIGIN } from '@/lib/env';
import { applySecurityHeaders } from '@/lib/security';
import { renderToBuffer } from '@react-pdf/renderer';
import { StudentCopyPDF } from '@/lib/pdf/student-copy';
import { TeacherCopyPDF } from '@/lib/pdf/teacher-copy';
import type { WorkbookOutput, QuestionOutput, RubricOutput } from '@/types';

const DEV_USER_ID = 'dev-user-00000000-0000-0000-0000-000000000000';

async function getUserId(): Promise<string | null> {
  if (!isSupabaseConfigured && process.env.NODE_ENV === 'development') return DEV_USER_ID;
  try {
    const supabase = await createClient();
    const { data } = await supabase.auth.getUser();
    return data.user?.id ?? null;
  } catch {
    return null;
  }
}

function parseJsonField<T>(value: string | null | undefined, fallback: T): T {
  if (!value) return fallback;
  try { return JSON.parse(value) as T; } catch { return fallback; }
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
): Promise<NextResponse> {
  const { id: workbookId } = await params;
  const { searchParams } = new URL(request.url);
  const type = searchParams.get('type') || 'student';
  const isTeacher = type === 'teacher';

  // ---- Auth ----
  const userId = await getUserId();
  if (!userId) {
    return NextResponse.json({ error: 'Authentication required.' }, { status: 401 });
  }

  // ---- Fetch workbook (scoped to owner) ----
  const wbRows = await db
    .select()
    .from(workbooks)
    .where(and(eq(workbooks.id, workbookId), eq(workbooks.userId, userId)))
    .limit(1);
  if (wbRows.length === 0) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }
  const wb = wbRows[0];

  // ---- Fetch questions ----
  const qRows = await db.select().from(questions)
    .where(eq(questions.workbookId, workbookId))
    .orderBy(questions.sortOrder);

  // ---- Fetch rubric ----
  const rRows = await db.select().from(rubrics)
    .where(eq(rubrics.workbookId, workbookId))
    .limit(1);

  // ---- Build WorkbookOutput ----
  const mappedQuestions: QuestionOutput[] = qRows.map((q) => ({
    type: q.type as QuestionOutput['type'],
    difficulty: q.difficulty as QuestionOutput['difficulty'],
    points: q.points,
    questionText: q.questionText,
    options: parseJsonField<string[] | null>(q.options, null) ?? undefined,
    correctAnswer: q.answer,
    solution: q.solution ?? '',
    standardCode: q.standardCode ?? undefined,
    confidence: q.confidence as QuestionOutput['confidence'],
  }));

  const mappedRubric: RubricOutput[] = rRows.map((r) => ({
    criteria: r.criteria,
    maxScore: r.maxScore,
    scoreLevels: parseJsonField<{ score: number; description: string }[]>(r.scoreLevels, []),
  }));

  const workbook: WorkbookOutput = {
    title: wb.title,
    subject: wb.subject,
    topic: wb.topic,
    gradeLevel: wb.gradeLevel,
    description: wb.description ?? '',
    estimatedTime: wb.estimatedTime ?? '',
    questions: mappedQuestions,
    rubric: mappedRubric,
  };

  // ---- Check plan for watermark ----
  const userRow = await db
    .select({ plan: users.plan })
    .from(users)
    .where(eq(users.id, userId))
    .limit(1);
  const isFreePlan = userRow[0]?.plan === 'free' || !userRow[0];

  // ---- Render PDF ----
  const pdfBuffer = await renderToBuffer(
    isTeacher ? (
      <TeacherCopyPDF workbook={workbook} />
    ) : (
      <StudentCopyPDF workbook={workbook} watermark={isFreePlan} />
    )
  );

  const filename = `${isTeacher ? 'TeacherCopy' : 'StudentCopy'}_${workbook.title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;

  const response = new NextResponse(new Uint8Array(pdfBuffer), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${encodeURIComponent(filename)}"`,
      'Content-Length': String(pdfBuffer.byteLength),
    },
  });

  applySecurityHeaders(response, { appOrigin: APP_ORIGIN });
  return response;
}
