/**
 * AI Generated Badge — OWASP LLM09 compliance
 *
 * Every AI-generated question must be clearly labeled to encourage
 * teacher review before classroom use.
 *
 * DESIGN.html §11: OWASP LLM Top 10 — LLM09 AI-label
 */

import { Sparkles } from 'lucide-react';

interface AIBadgeProps {
  className?: string;
  size?: 'sm' | 'md';
}

export function AIBadge({ className = '', size = 'sm' }: AIBadgeProps) {
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full bg-amber-100 px-2 py-0.5 text-${size === 'sm' ? 'xs' : 'sm'} font-medium text-amber-800 dark:bg-amber-900/30 dark:text-amber-300 ${className}`}
      title="This content was generated by AI. Please review before using in class."
    >
      <Sparkles className={size === 'sm' ? 'h-3 w-3' : 'h-3.5 w-3.5'} aria-hidden="true" />
      AI-Generated
    </span>
  );
}
